workflows:
  default:
    name: Flutter or Dart Package
    environment:
      flutter: beta
      vars:
        CODECOV_TOKEN: Encrypted(Z0FBQUFBQmZrMURMX0wxbDJaWXNJeDVaX1gwRm5CNHJITUxJU1N6X2lCRGlfcTRBZHhTdmE4RzNobm9QMi10QlJYcm1mVnpXeG5udXB6UjFxTl9tR3ZHLW11NUhkckFfYUZ0SEtLWHRDNDk4NTNVRUF1TVRYRWVfSnlDWmFoaEVSSjVvTjBoX0xmZU8=)
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: false
      cancel_previous_builds: false 
    scripts:
      - flutter packages pub get
      - flutter test
      - name: Coverage Test
        script: |
          #!/bin/bash
          flutter test --coverage
          bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
